// <auto-generated />
using System;
using AppServer_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServer_Project.Migrations
{
    [DbContext(typeof(ServersContext))]
    [Migration("20230502183104_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppServer_Project.Models.GameServer", b =>
                {
                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<float>("CpuUsage")
                        .HasColumnType("real");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("real");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTimeMin")
                        .HasColumnType("int");

                    b.Property<string>("ServerRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ServerUp")
                        .HasColumnType("bit");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.HasKey("ServerName", "DateTime");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
